import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Container from "@/components/Container/Index";
import Header from "@/components/Header/Index";
import Content from "@/components/Content/Index";
import Footer from "@/components/Footer/Index";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Home | Bug2Fix",
    template: "%s | Bug2Fix",
  },
 
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container>
          <Content>
            <Header />
            {children}
            <Footer />
          </Content>
        </Container>
      </body>
    </html>
  );
}
